language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm Carton && carton install"
script:
  - "carton exec -- prove -lr t"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
